services:
  - type: web
    name: chatbot-cengicana
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port=$PORT --server.enableCORS=false"
    envVars:
      - key: OPENAI_API_KEY
        value: sk-xxxxxxx  # ← reemplaza luego desde Render con variable segura
